version: '3'
services: 
  uncomplited:
    container_name: ssh-uncomplited
    build: ./app/
    restart: always
    ports:
      - "2022:22"
    healthcheck:
      test: ["CMD", "socat", "TCP4:localhost:22", "-"]
      interval: 57s
      timeout: 3s
      retries: 1
