version: '3'
services:
  ofelia:
    container_name: ofelia-uncomplited 
    image: mcuadros/ofelia:latest
    depends_on:
      - uncomplited 
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  uncomplited:
    container_name: ssh-uncomplited
    build: ./app/
    restart: always
    ports:
      - "2022:22"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.rmgarbage.schedule: "@every 1m"
      ofelia.job-exec.rmgarbage.command: sh -c 'rm -rf /tmp/* && rm -rf /home/user/*'
    healthcheck:
      test: ["CMD", "socat", "TCP4:localhost:22", "-"]
      interval: 57s
      timeout: 3s
      retries: 1

